// <auto-generated />
using System;
using Digital_Art_Kursoviy_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digital_Art_Kursoviy_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518192644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admininstrators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gallery.com",
                            FullName = "Головний Куратор",
                            IsSuperAdmin = true,
                            Password = "gallery2024",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Італійський вчений, винахідник, художник.",
                            BirthYear = 1452,
                            ContactInfo = "Немає",
                            DeathYear = 1519,
                            FullName = "Леонардо да Вінчі",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/b/ba/Leonardo_self.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Американська художниця, відома своїми глибокими та сюрреалістичними полотнами.",
                            BirthYear = 1995,
                            ContactInfo = "rae.klein@art.com",
                            FullName = "Rae Klein",
                            PhotoUrl = "https://picsum.photos/seed/artist1/300/300"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Українська художниця, що створює містичні світи.",
                            BirthYear = 1998,
                            ContactInfo = "maria.art@ukr.net",
                            FullName = "Maria Prisyazhnuk",
                            PhotoUrl = "https://picsum.photos/seed/artist2/300/300"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Майстриня емоційних портретів. Її роботи відрізняються деталізацією.",
                            BirthYear = 1990,
                            ContactInfo = "nisha@boehm.art",
                            FullName = "Nisha Boehm",
                            PhotoUrl = "https://picsum.photos/seed/artist3/300/300"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Легендарна фотографиня. Працює зі світлом та тінню.",
                            BirthYear = 1949,
                            ContactInfo = "contact@leibovitz.studio",
                            FullName = "Енні Лейбовіц",
                            PhotoUrl = "https://picsum.photos/seed/artist4/300/300"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Один із засновників сучасної скульптури.",
                            BirthYear = 1840,
                            ContactInfo = "Музей Родена",
                            DeathYear = 1917,
                            FullName = "Огюст Роден",
                            PhotoUrl = "https://picsum.photos/seed/artist5/300/300"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Штучний інтелект, навчений на мільйонах зображень.",
                            BirthYear = 2022,
                            ContactInfo = "midjourney.com",
                            FullName = "Midjourney v6",
                            PhotoUrl = "https://picsum.photos/seed/artist6/300/300"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Artworks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Artwork");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Центральний зал для змішаних виставок",
                            Name = "Головна експозиція"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Простір традиційного образотворчого мистецтва",
                            Name = "Картини та полотна"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Зал цифрових технологій, медіа-арту та ШІ",
                            Name = "Мультимедійна зона"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Простір для скульптур та тривимірних об'єктів",
                            Name = "Зал об'ємних інсталяцій"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.AIArt", b =>
                {
                    b.HasBaseType("Digital_Art_Kursoviy_Project.Models.Artwork");

                    b.Property<string>("AIModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AIArt");

                    b.HasData(
                        new
                        {
                            Id = 29,
                            ArtistId = 15,
                            CategoryId = 3,
                            CreationYear = 2026,
                            CurrentStateName = "OnDisplay",
                            Description = "Генерація за мотивами кіберпанк-майбутнього.",
                            ImageUrl = "https://picsum.photos/seed/art10/800/600",
                            Material = "Пікселі",
                            Technique = "Text-to-Image",
                            Title = "Neon Genesis",
                            AIModelVersion = "Midjourney v6",
                            GenerationPrompt = "Cyberpunk city, neon lights"
                        },
                        new
                        {
                            Id = 30,
                            ArtistId = 15,
                            CategoryId = 3,
                            CreationYear = 2026,
                            CurrentStateName = "OnDisplay",
                            Description = "Подорож у підсвідомість штучного інтелекту.",
                            ImageUrl = "https://picsum.photos/seed/art11/800/600",
                            Material = "Пікселі",
                            Technique = "Prompt Engineering",
                            Title = "Surreal Mindscape",
                            AIModelVersion = "DALL-E 3",
                            GenerationPrompt = "Surreal landscape, melting clocks"
                        },
                        new
                        {
                            Id = 31,
                            ArtistId = 15,
                            CategoryId = 3,
                            CreationYear = 2026,
                            CurrentStateName = "OnDisplay",
                            Description = "Спроба ШІ відтворити стиль ренесансу.",
                            ImageUrl = "https://picsum.photos/seed/art12/800/600",
                            Material = "Пікселі",
                            Technique = "Stable Diffusion",
                            Title = "Echoes of Yesteryear",
                            AIModelVersion = "Stable Diffusion XL",
                            GenerationPrompt = "Renaissance portrait of a lady"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.DigitalArt", b =>
                {
                    b.HasBaseType("Digital_Art_Kursoviy_Project.Models.Artwork");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DigitalArt");

                    b.HasData(
                        new
                        {
                            Id = 23,
                            ArtistId = 11,
                            CategoryId = 3,
                            CreationYear = 2025,
                            CurrentStateName = "OnDisplay",
                            Description = "Цифровий сюрреалізм на межі сну і реальності.",
                            ImageUrl = "https://picsum.photos/seed/art4/800/600",
                            Material = "Digital",
                            Technique = "Procreate",
                            Title = "Fragmented Reality",
                            Resolution = "3840x2160 (4K)",
                            SoftwareUsed = "Procreate"
                        },
                        new
                        {
                            Id = 24,
                            ArtistId = 11,
                            CategoryId = 3,
                            CreationYear = 2024,
                            CurrentStateName = "Archived",
                            Description = "Візуалізація того, як машини бачать власні сни.",
                            ImageUrl = "https://picsum.photos/seed/art5/800/600",
                            Material = "Digital",
                            Technique = "Photoshop",
                            Title = "Cybernetic Dreams",
                            Resolution = "1920x1080 (Full HD)",
                            SoftwareUsed = "Adobe Photoshop"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Painting", b =>
                {
                    b.HasBaseType("Digital_Art_Kursoviy_Project.Models.Artwork");

                    b.Property<string>("CanvasType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Painting");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            ArtistId = 10,
                            CategoryId = 2,
                            CreationYear = 2023,
                            CurrentStateName = "OnDisplay",
                            Description = "Сюрреалістичний погляд на самотність і тишу.",
                            ImageUrl = "https://picsum.photos/seed/art1/800/600",
                            Material = "Полотно",
                            Technique = "Олія",
                            Title = "Silent Observer",
                            CanvasType = "Льон"
                        },
                        new
                        {
                            Id = 21,
                            ArtistId = 10,
                            CategoryId = 2,
                            CreationYear = 2024,
                            CurrentStateName = "OnDisplay",
                            Description = "Напруга і спокій в одному моменті.",
                            ImageUrl = "https://picsum.photos/seed/art2/800/600",
                            Material = "Дерево",
                            Technique = "Акрил",
                            Title = "The Red Ribbon",
                            CanvasType = "Бавовна"
                        },
                        new
                        {
                            Id = 22,
                            ArtistId = 12,
                            CategoryId = 2,
                            CreationYear = 2022,
                            CurrentStateName = "OnDisplay",
                            Description = "Роздуми про плинність часу.",
                            ImageUrl = "https://picsum.photos/seed/art3/800/600",
                            Material = "Полотно",
                            Technique = "Олія",
                            Title = "Echoes of Time",
                            CanvasType = "Льон"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Photography", b =>
                {
                    b.HasBaseType("Digital_Art_Kursoviy_Project.Models.Artwork");

                    b.Property<string>("CameraModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LensType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Photography");

                    b.HasData(
                        new
                        {
                            Id = 25,
                            ArtistId = 13,
                            CategoryId = 1,
                            CreationYear = 1999,
                            CurrentStateName = "OnDisplay",
                            Description = "Класичний портрет.",
                            ImageUrl = "https://picsum.photos/seed/art6/800/600",
                            Material = "Фотопапір",
                            Technique = "Чорно-біла плівка",
                            Title = "Monochrome Portrait",
                            CameraModel = "Leica M6",
                            LensType = "35mm f/1.4"
                        },
                        new
                        {
                            Id = 26,
                            ArtistId = 13,
                            CategoryId = 1,
                            CreationYear = 2010,
                            CurrentStateName = "OnDisplay",
                            Description = "Гра світла і тіні у великому мегаполісі.",
                            ImageUrl = "https://picsum.photos/seed/art7/800/600",
                            Material = "Digital",
                            Technique = "Цифрова фотографія",
                            Title = "Urban Shadows",
                            CameraModel = "Sony A7R IV",
                            LensType = "24-70mm f/2.8"
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Sculpture", b =>
                {
                    b.HasBaseType("Digital_Art_Kursoviy_Project.Models.Artwork");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Sculpture");

                    b.HasData(
                        new
                        {
                            Id = 27,
                            ArtistId = 14,
                            CategoryId = 4,
                            CreationYear = 1904,
                            CurrentStateName = "OnDisplay",
                            Description = "Символ людського інтелекту.",
                            ImageUrl = "https://picsum.photos/seed/art8/800/600",
                            Material = "Бронза",
                            Technique = "Лиття",
                            Title = "The Thinker",
                            MaterialType = "Метал",
                            WeightKg = 0.0
                        },
                        new
                        {
                            Id = 28,
                            ArtistId = 14,
                            CategoryId = 4,
                            CreationYear = 1882,
                            CurrentStateName = "Restoration",
                            Description = "Вічне кохання, застигле у камені.",
                            ImageUrl = "https://picsum.photos/seed/art9/800/600",
                            Material = "Мармур",
                            Technique = "Різьблення",
                            Title = "The Kiss",
                            MaterialType = "Камінь",
                            WeightKg = 0.0
                        });
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Artwork", b =>
                {
                    b.HasOne("Digital_Art_Kursoviy_Project.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital_Art_Kursoviy_Project.Models.Category", "Category")
                        .WithMany("Artworks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Category", b =>
                {
                    b.HasOne("Digital_Art_Kursoviy_Project.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("Digital_Art_Kursoviy_Project.Models.Category", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
